TEST_VALUE:
  name: 'dev_cookie'

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a25ba3dbda3a5013
  FEISHU_APP_SECRET: M5bwgHB3lGVlB2q8Di8IShy8SgkbkW4i
  APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
  USER_TOKEN_CACHE_KEY: USER_TOKEN_CACHE_KEY
  USER_REFRESH_TOKEN_CACHE_KEY: USER_REFRESH_TOKEN_CACHE_KEY

MONGODB_CONFIG:
  name: 'fast_gateway' # 自定义次数据库链接名称
  type: mongodb # 数据库链接类型
  url: 'mongodb://localhost:27017' # 数据库链接地址
  username: '' # 数据库链接用户名
  password: '' # 数据库链接密码
  database: 'fast_gateway' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能

REDIS_CONFIG:
  host: 'localhost' # redis 链接
  port: 6379 # redis 端口
  auth: '' # redis 连接密码
  db: 1 # redis 数据库
